---
#Created by Khai Hoang (Kyle)
#Project:DEVOPS16
#Description: Install Docker playbook
- name: Install docker
  hosts: test
  gather_facts: no
  become: true

  tasks:
    - name: Installing Docker Prerequisite packages
      yum:
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo

    - name: Install Docker
      package:
        name: docker-ce
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'